routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\AccountController;
use App\Http\Controllers\BrandController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\MaterialController;
use App\Http\Controllers\SupplierController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\UserAccountController;
use App\Http\Controllers\StockController;
use App\Http\Controllers\LogController;
use App\Http\Controllers\SupportController;

 
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () {
    return view('Auth.index');
})->name('login');




//Authentications/Login
Route::group(['prefix'=> 'auth', 'as' => 'auth.'], function(){
	// For Login
	Route::controller(AuthController::class)->group(function () {
 		 Route::post('request', 'authenticate')->name('authenticate');
	});
});


Route::group(['prefix' => 'user_accounts', 'as' => 'user_accounts.'], function(){
	Route::controller(UserAccountController::class)->group(function () {
		Route::get('', 'index')->name('index');
		Route::get('list', 'list')->name('list');
		Route::post('save/{id?}', 'save')->name('save');
		Route::get('find/{id?}', 'find')->name('find');
		Route::get('toggle/{id?}/{status?}', 'toggle')->name('toggle');
	});
});


Route::group(['middleware' => ['auth']], function(){
    Route::get('logout', [AuthController::class, 'logout'])->name('logout');

    // Dashboard
    Route::get('dashboard', [DashboardController::class, 'index'])->name('dashboard');
 


	// Brands
Route::group(['prefix' => 'brands', 'as' => 'brands.'], function(){
	Route::controller(BrandController::class)->group(function () {
		Route::get('', 'index')->name('index');
		Route::get('list', 'list')->name('list');
		Route::post('save/{id?}', 'save')->name('save');
		Route::get('find/{id?}', 'find')->name('find');
		Route::delete('delete/{id?}', 'delete')->name('delete');
	});
});
	// Category
	Route::group(['prefix' => 'categories', 'as' => 'categories.'], function(){
		Route::controller(CategoryController::class)->group(function () {
			Route::get('', 'index')->name('index');
			Route::get('list', 'list')->name('list');
			Route::post('save/{id?}', 'save')->name('save');
			Route::get('find/{id?}', 'find')->name('find');
			Route::delete('delete/{id?}', 'delete')->name('delete');
		});
	});

	


	//product
	Route::group(['prefix' => 'products', 'as' => 'products.'], function(){
		Route::controller(ProductController::class)->group(function () {
			Route::get('', 'index')->name('index');
			Route::get('list', 'list')->name('list');
			Route::get('add', 'add')->name('add');
			Route::get('edit/{id?}', 'edit')->name('edit');
			Route::post('save/{id?}', 'save')->name('save');
			Route::get('find/{id?}', 'find')->name('find');
			Route::delete('delete/{id?}', 'delete')->name('delete');
		});
	});

	// Material
	Route::group(['prefix' => 'materials', 'as' => 'materials.'], function(){
		Route::controller(MaterialController::class)->group(function () {
			Route::get('', 'index')->name('index');
			Route::get('list', 'list')->name('list');
			Route::post('save/{id?}', 'save')->name('save');
			Route::get('find/{id?}', 'find')->name('find');
			Route::delete('delete/{id?}', 'delete')->name('delete');
		});
	});

	//supplier
	Route::group(['prefix' => 'suppliers', 'as' => 'suppliers.'], function(){
		Route::controller(SupplierController::class)->group(function () {
			Route::get('', 'index')->name('index');
			Route::get('list', 'list')->name('list');
			Route::post('save/{id?}', 'save')->name('save');
			Route::get('find/{id?}', 'find')->name('find');
			Route::delete('delete/{id?}', 'delete')->name('delete');
		});
	});


	//customer
	Route::group(['prefix' => 'customers', 'as' => 'customers.'], function(){
		Route::controller(CustomerController::class)->group(function () {
			Route::get('', 'index')->name('index');
			Route::get('list', 'list')->name('list');
			Route::post('save/{id?}', 'save')->name('save');
			Route::get('find/{id?}', 'find')->name('find');
			Route::delete('delete/{id?}', 'delete')->name('delete');
		});
	});

	//orders
	Route::group(['prefix' => 'orders', 'as' => 'orders.'], function(){
		Route::controller(OrderController::class)->group(function () {
			Route::get('', 'index')->name('index');
			Route::post('items', 'getItemFromCode')->name('get.items');
			Route::get('list', 'list')->name('list');
			Route::get('add', 'add')->name('add');
			Route::get('edit/{id?}', 'edit')->name('edit');
			Route::post('save/{id?}', 'save')->name('save');
			Route::get('find/{id?}', 'find')->name('find');
			Route::delete('delete/{id?}', 'delete')->name('delete');
			Route::post('payment', 'payment')->name('payment');
		});
	});

	// Stocks

	Route::group(['prefix' => 'stocks', 'as' => 'stocks.'], function(){
		Route::controller(StockController::class)->group(function () {
			Route::get('{type?}', 'index')->name('index');
			Route::get('list/{type?}', 'list')->name('list');
			Route::post('save/{stock_id?}', 'save')->name('save');
			Route::get('find/{stock_id?}', 'find')->name('find');
			Route::get('find-stocks/{id?}/{type?}', 'findItems')->name('find.items');
			Route::get('find-stocks-code/{code?}/{type?}', 'findItemsCode')->name('find.items.code');
			Route::delete('delete/{stock_id?}', 'delete')->name('delete');
		});
	});

	//activity logs
	Route::group(['prefix' => 'logs', 'as' => 'logs.'], function(){
		Route::controller(LogController::class)->group(function () {
			Route::get('', 'index')->name('index');
			Route::get('list', 'list')->name('list');
		});
	});

	//activity logs
	Route::group(['prefix' => 'support', 'as' => 'support.'], function(){
		Route::controller(SupportController::class)->group(function () {
			Route::get('', 'index')->name('index');
			Route::get('list', 'list')->name('list');
		});
	});


});


/* Put it at the top */

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\User;
use Validator;

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Session;


class DashboardController extends Controller
{
	public function index(){

		// return orderDashboard();
		return view('Dashboard.index');
	}
}

resources/views/Dashboard/index.blade.php
@extends('Layout.admin_app')
@section('title', 'Dashboard')
@section('content')
<div class="container-fluid pt-3">
	<div class="row mb-3">
		<div class="col-lg-4 col-6">
			<div class="small-box bg-info">
				<div class="inner">
					<h3>{{getProductCount() }} <sup style="font-size: 15px">(QTY:{{ getProductCountQTY() }})</sup></h3>
					<p>Products</p>
				</div>
				<div class="icon">
					<i class="fas fa-dolly-flatbed"></i>
				</div>
				<a href="{{ route('products.index') }}" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
			</div>
		</div>
		<div class="col-lg-4 col-6">
			<div class="small-box bg-success">
				<div class="inner">
					<h3>{{getMaterialCount() }} <sup style="font-size: 15px">(QTY:{{ getMaterialCountQTY() }})</sup></h3>
					<p>Raw Materials</p>
				</div>
				<div class="icon">
					<i class="far fa-dot-circle"></i>
				</div>
				<a href="{{ route('materials.index') }}" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
			</div>
		</div>
		<div class="col-lg-4 col-6">
			<div class="small-box bg-warning">
				<div class="inner">
					<h3>{{getCustomerCount() }}</h3>
					<p>Customers</p>
				</div>
				<div class="icon">
					<i class="fas fa-people-carry"></i>
				</div>
				<a href="{{ route('customers.index') }}" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
			</div>
		</div>
		<div class="col-lg-6 col-6">
			<div class="small-box bg-primary">
				<div class="inner">
					<h3>{{getOrderCountCompleted() }}</h3>
					<p>Completed Orders</p>
				</div>
				<div class="icon">
					<i class="fas fa-shipping-fast"></i>
				</div>
				<a href="{{ route('orders.index') }}" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
			</div>
		</div>
		<div class="col-lg-6 col-6">
			<div class="small-box bg-danger">
				<div class="inner">
					<h3>{{getOrderCount() }}</h3>
					<p>Pending Orders</p>
				</div>
				<div class="icon">
					<i class="fas fa-shipping-fast"></i>
				</div>
				<a href="{{ route('orders.index') }}" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
			</div>
		</div>
		<div class="col-md-12 mt-2">

			@if(getAlertMaterialsCheck() > 0 || getAlertProductsCheck() > 0)
				<div class="alert alert-info alert-dismissible animated slideInDown" role="alert">
				  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				  <strong><i class="fas fa-lightbulb"></i> Decision Support</strong>, Better check your stocks regularly!
				</div>
			@else
				<div class="alert alert-success alert-dismissible animated slideInDown" role="alert">
				  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				   <strong><i class="fas fa-lightbulb"></i> Decision Support</strong>, Stocks are great today!
				</div>
			@endif


			@if(getAlertMaterialsCheck() > 0)
			<a href="{{ route('support.index') }}">
				<div class="alert alert-danger animated slideInDown alert-dismissible" role="alert">
				  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				  <strong><i class="fa fa-exclamation-circle"></i></strong> <b>Raw Materials</b> stocks are not looking good.
				</div>
			</a>
			@endif



			@if(getAlertProductsCheck() > 0)
			<a href="{{ route('support.index') }}">
				<div class="alert alert-danger animated slideInDown alert-dismissible" role="alert">
				  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				  <strong><i class="fa fa-exclamation-circle"></i></strong> <b>Products</b> stocks are not looking good.
				</div>
			</a>
				@endif
		</div>
		<div class="col-md-12">
			<div class="card card-info">
				<div class="card-header">
					<h3 class="card-title">Order Analytics - {{ date('Y') }}</h3>
					<div class="card-tools">
						<button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-minus"></i></button>
					</div>
				</div>
				<div class="card-body">
					<div class="chart"><div class="chartjs-size-monitor"><div class="chartjs-size-monitor-expand"><div class=""></div></div><div class="chartjs-size-monitor-shrink"><div class=""></div></div></div>
						<canvas id="barChart" style="min-height: 250px; height: 250px; max-height: 250px; max-width: 100%; display: block; width: 764px;" width="764" height="250" class="chartjs-render-monitor"></canvas>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
@include('StockFlow.modal')
@endsection


@section('script')
@include('StockFlow.script')
<script src="{{ asset('adminLTE/plugins/chart.js/Chart.min.js') }}"></script>
<script>
	$("#table_materials").dataTable();
	$("#table_products").dataTable();
</script>

<script type="text/javascript">
	$(function () {
    /* ChartJS
     * -------
     * Here we will create a few charts using ChartJS
     */

    //--------------
    //- AREA CHART -
    //--------------

    // Get context with jQuery - using jQuery's .get() method.

    var areaChartData = {
      labels  : JSON.parse('{!! json_encode(orderDashboard()['labels']) !!}'),
      datasets: [
        {
          label               : 'Completed',
          backgroundColor     : 'rgba(60,141,188,0.9)',
          borderColor         : 'rgba(60,141,188,0.8)',
          pointRadius          : false,
          pointColor          : '#3b8bba',
          pointStrokeColor    : 'rgba(60,141,188,1)',
          pointHighlightFill  : '#fff',
          pointHighlightStroke: 'rgba(60,141,188,1)',
          data                : JSON.parse('{!! json_encode(orderDashboard()['completed']) !!}')
        },
        {
          label               : 'Pending',
          backgroundColor     : 'rgba(210, 214, 222, 1)',
          borderColor         : 'rgba(210, 214, 222, 1)',
          pointRadius         : false,
          pointColor          : 'rgba(210, 214, 222, 1)',
          pointStrokeColor    : '#c1c7d1',
          pointHighlightFill  : '#fff',
          pointHighlightStroke: 'rgba(220,220,220,1)',
          data                : JSON.parse('{!! json_encode(orderDashboard()['pending']) !!}')
        },
      ]
    }

    //-------------
    //- BAR CHART -
    //-------------
    var barChartCanvas = $('#barChart').get(0).getContext('2d')
    var barChartData = $.extend(true, {}, areaChartData)
    var temp0 = areaChartData.datasets[0]
    var temp1 = areaChartData.datasets[1]
    barChartData.datasets[0] = temp1
    barChartData.datasets[1] = temp0

    var barChartOptions = {
      responsive              : true,
      maintainAspectRatio     : false,
      datasetFill             : false
    }

    new Chart(barChartCanvas, {
      type: 'bar',
      data: barChartData,
      options: barChartOptions
    })

    //---------------------
    //- STACKED BAR CHART -
    //---------------------
    var stackedBarChartCanvas = $('#stackedBarChart').get(0).getContext('2d')
    var stackedBarChartData = $.extend(true, {}, barChartData)

    var stackedBarChartOptions = {
      responsive              : true,
      maintainAspectRatio     : false,
      scales: {
        xAxes: [{
          stacked: true,
          precision: 0
        }],
        yAxes: [{
          	stacked: true,
        }]
      }
    }

    new Chart(stackedBarChartCanvas, {
      type: 'bar',
      data: stackedBarChartData,
      options: stackedBarChartOptions
    })
  })
</script>
@endsection

resources/views/Dashboard/userManagement.blade.php
@extends('Layout.admin_app')
@section('title', 'Dashboard')
@section('content')

this is user management
<div class="row">
	<div class="col-lg-12 col-md-12 col-12">
		<div class="border-bottom pb-4 mb-4 d-md-flex justify-content-between align-items-center">
			<div class="mb-3 mb-md-0">
				<h1 class="mb-1 h2 fw-bold">Users</h1>
				@include('Layout.bread', ['data' => [ 'Users' => url()->current() ] ])
			</div>
			<div class="d-flex">
				  <button class="btn btn-primary btn-shadow" onclick="add_Users();"><i class="fa fa-plus"></i> Add Users</button>
			</div>
		</div>
	</div>
</div>

<div class="card">
	<div class="card-body">
		<div class="table-responsive">
			<table class="table table-bordered dt-responsive nowrap" id="tbl_Users" style="width: 100%;"></table>
		</div>
	</div>
</div>

<form class="needs-validation" id="user_reg_form" action="{{ url('Users/add') }}" novalidate>
	<div class="modal fade" role="dialog" id="modal_Users" data-bs-backdrop="static">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<div class="modal-title" id="modal_title_Users">
					Add Users
				</div>
				<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
			</div>
			<div class="modal-body">
				<div class="row">
					<input type="hidden" id="user_id" name="user_id" placeholder="" class="form-control" required>
					<div class="position-relative mb-2 col-sm-12">
						<label>User Id </label>
						<input type="hidden" id="user_id" name="user_id" placeholder="" class="form-control " required>
						<div class="invalid-feedback" id="err_user_id"></div>
					</div>
					<div class="position-relative mb-2 col-sm-6">
						<label>Firstname </label>
						<input type="text" id="Firstname" name="Firstname" placeholder="Enter Firstname" class="form-control " required>
						<div class="invalid-feedback" id="err_Firstname"></div>
					</div>
					<div class="position-relative mb-2 col-sm-6">
						<label>Middlename </label>
						<input type="text" id="Middlename" name="Middlename" placeholder="Enter Middlename" class="form-control " required>
						<div class="invalid-feedback" id="err_Middlename"></div>
					</div>
					<div class="position-relative mb-2 col-sm-12">
						<label>Lastname </label>
						<input type="text" id="Lastname" name="Lastname" placeholder="Enter Lastname" class="form-control " required>
						<div class="invalid-feedback" id="err_Lastname"></div>
					</div>
					<div class="position-relative mb-2 col-sm-6">
						<label>Gender </label>
						<select id="gender" name="gender" class="form-control ">
							<option value="Male">Male</option>
							<option value="Female">Female</option>
							<option value="Other">Other</option>
						</select>
						<div class="invalid-feedback" id="err_gender"></div>
					</div>
						<div class="position-relative mb-2 col-sm-6">
						<label>Contact </label>
						<input type="text" id="contact" name="contact" placeholder="Enter contact number here" class="form-control " required>
						<div class="invalid-feedback" id="err_contact"></div>
					</div>
					<div class="position-relative mb-2 col-sm-6">
						<label>Province </label>
						<input type="text" id="province" name="province" placeholder="Enter province here" class="form-control " required>
						<div class="invalid-feedback" id="err_province"></div>
					</div>
					<div class="position-relative mb-2 col-sm-6">
						<label>City </label>
						<input type="text" id="city" name="city" placeholder="Enter city here" class="form-control " required>
						<div class="invalid-feedback" id="err_city"></div>
					</div>
					<div class="position-relative mb-2 col-sm-12">
						<label>Brgy </label>
						<input type="text" id="brgy" name="brgy" placeholder="Enter barangay here" class="form-control " required>
						<div class="invalid-feedback" id="err_brgy"></div>
					</div>
					<div class="position-relative mb-2 col-sm-12">
						<label>Address </label>
						<input type="text" id="address" name="address" placeholder="Enter address here" class="form-control " required>
						<div class="invalid-feedback" id="err_address"></div>
					</div>
					<div class="position-relative mb-2 col-sm-12">
						<label>Email </label>
						<input type="email" id="Email" name="Email" placeholder="Enter email here" class="form-control " required>
						<div class="invalid-feedback" id="err_Email"></div>
					</div>
					<div class="position-relative mb-2 col-sm-12">
						<label>Password </label>
						<input type="password" id="Password" name="Password" placeholder="Enter password" class="form-control " required>
						<div class="invalid-feedback" id="err_Password"></div>
					</div>
				</div>
			</div>
			<div class="modal-footer d-block">
				<div class="row">
					<div class="col-sm-6 col-12">
						<button class="btn btn-dark col-sm-12 col-12" data-bs-dismiss="modal" type="button">Cancel</button>
					</div>
					<div class="col-sm-6 col-12">
						<button class="btn btn-success col-sm-12 col-12" id="btn_submit_Users" type="submit">Save</button>
					</div>
				</div>
			</div>
		</div>
	</div>
	</div>
</form>
@endsection
@section('script')
<!-- Javascript Function-->
<script>
show_Users();
	var tbl_Users;
	function show_Users(){
		if (tbl_Users) {
			tbl_Users.destroy();
		}
		var url = main_path + 'Users/list';
		tbl_Users = $('#tbl_Users').DataTable({
		pageLength: 10,
		responsive: true,
		ajax: url,
		deferRender: true,
		language: {
		"emptyTable": "No data available"
	},
		columns: [{
		className: '',
		"data": "user_id",
		"title": "User id",
	},{
		className: '',
		"data": "Firstname",
		"title": "Firstname",
	},{
		className: '',
		"data": "Middlename",
		"title": "Middlename",
	},{
		className: '',
		"data": "Lastname",
		"title": "Lastname",
	},{
		className: '',
		"data": "gender",
		"title": "Gender",
	},{
		className: '',
		"data": "contact",
		"title": "Contact",
	},{
		className: '',
		"data": "province",
		"title": "Province",
	},{
		className: '',
		"data": "city",
		"title": "City",
	},{
		className: '',
		"data": "brgy",
		"title": "Brgy",
	},{
		className: '',
		"data": "address",
		"title": "Address",
	},{
		className: '',
		"data": "Email",
		"title": "Email",
	},{
		className: '',
		"data": "Password",
		"title": "Password",
	},{
		className: 'width-option-1 text-center',
		"data": "user_id",
		"orderable": false,
		"title": "Options",
			"render": function(data, type, row, meta){
				newdata = '';
				newdata += '<button class="btn btn-success btn-sm font-base mt-1" data-id=\' '+row.user_id+'\' onclick="edit_Users(this)" type="button"><i class="fa fa-edit"></i></button> ';
				newdata += ' <button class="btn btn-danger btn-sm font-base mt-1" data-id=\' '+row.user_id+'\' onclick="delete_Users(this)" type="button"><i class="fa fa-trash"></i></button>';
				return newdata;
			}
		}
	]
	});
	}

	$("#user_reg_form").on('submit', function(e){
		var url = $(this).attr('action');
		var mydata = $(this).serialize();
		e.stopPropagation();
		e.preventDefault(e);

		$.ajax({
			type:"POST",
			url:url,
			data:mydata,
			cache:false,
			beforeSend:function(){
					//<!-- your before success function -->
					$('#btn_submit_Users').prop('disabled', true);
					$('#btn_submit_Users').text('Please wait...');
			},
			success:function(response){
					//console.log(response)
				if(response.status == true){
					console.log(response)
					swal("Success", response.message, "success");
					showValidator(response.error,'user_reg_form');
					show_Users();
					$('#modal_Users').modal('hide');
				}else{
					//<!-- your error message or action here! -->
					showValidator(response.error,'user_reg_form');
				}
				$('#btn_submit_Users').prop('disabled', false);
				$('#btn_submit_Users').text('Save');
			},
			error:function(error){
				console.log(error)
			}
		});
	});

	function delete_Users(_this){
		var id = $(_this).attr('data-id');
		var url =  main_path + 'Users/delete/' + id;
			swal({
				title: "Are you sure?",
				text: "Do you want to delete this Users?",
				type: "warning",
				showCancelButton: true,
				confirmButtonColor: "#DD6B55",
				confirmButtonText: "Yes",
				closeOnConfirm: false
			},
			function(){
				$.ajax({
				type:"delete",
				url:url,
				data:{},
				dataType:'json',
				beforeSend:function(){
			},
			success:function(response){
				// console.log(response);
				if (response.status == true) {
					swal("Success", response.message, "success");
					show_Users();
				}else{
					console.log(response);
				}
			},
			error: function(error){
				console.log(error);
			}
			});
		});
	}

	function add_Users(){
		$('#modal_title_Users').text('Add Users');
		$('#user_id').val('');
		showValidator([],'user_reg_form');
		$('#user_reg_form').removeClass('was-validated');
		$('#user_id').val('');
		$('#Firstname').val('');
		$('#Middlename').val('');
		$('#Lastname').val('');
		$('#gender').val('');
		$('#contact').val('');
		$('#province').val('');
		$('#city').val('');
		$('#brgy').val('');
		$('#address').val('');
		$('#Email').val('');
		$('#Password').val('');
		$('#modal_Users').modal('show');
	}

	function edit_Users(_this){
		$('#modal_title_Users').text('Edit Users');
		var id = $(_this).attr('data-id');
		var url =  main_path + 'Users/find/' + id;
		$.ajax({
		type:"get",
		url:url,
		data:{},
		dataType:'json',
			beforeSend:function(){
		},
		success:function(response){
			let data = response.data;
			$('#user_id').val(data.user_id);
			$('#user_id').val(data.user_id);
			$('#Firstname').val(data.Firstname);
			$('#Middlename').val(data.Middlename);
			$('#Lastname').val(data.Lastname);
			$('#gender').val(data.gender);
			$('#contact').val(data.contact);
			$('#province').val(data.province);
			$('#city').val(data.city);
			$('#brgy').val(data.brgy);
			$('#address').val(data.address);
			$('#Email').val(data.Email);
			$('#Password').val(data.Password);
			$('#modal_Users').modal('show');
		},
		error: function(error){
			console.log(error);
		}
		});
	}
</script>
@endsection