routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\AccountController;
use App\Http\Controllers\BrandController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\MaterialController;
use App\Http\Controllers\SupplierController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\UserAccountController;
use App\Http\Controllers\StockController;
use App\Http\Controllers\LogController;
use App\Http\Controllers\SupportController;

 
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () {
    return view('Auth.index');
})->name('login');




//Authentications/Login
Route::group(['prefix'=> 'auth', 'as' => 'auth.'], function(){
	// For Login
	Route::controller(AuthController::class)->group(function () {
 		 Route::post('request', 'authenticate')->name('authenticate');
	});
});


Route::group(['prefix' => 'user_accounts', 'as' => 'user_accounts.'], function(){
	Route::controller(UserAccountController::class)->group(function () {
		Route::get('', 'index')->name('index');
		Route::get('list', 'list')->name('list');
		Route::post('save/{id?}', 'save')->name('save');
		Route::get('find/{id?}', 'find')->name('find');
		Route::get('toggle/{id?}/{status?}', 'toggle')->name('toggle');
	});
});


Route::group(['middleware' => ['auth']], function(){
    Route::get('logout', [AuthController::class, 'logout'])->name('logout');

    // Dashboard
    Route::get('dashboard', [DashboardController::class, 'index'])->name('dashboard');
 


	// Brands
Route::group(['prefix' => 'brands', 'as' => 'brands.'], function(){
	Route::controller(BrandController::class)->group(function () {
		Route::get('', 'index')->name('index');
		Route::get('list', 'list')->name('list');
		Route::post('save/{id?}', 'save')->name('save');
		Route::get('find/{id?}', 'find')->name('find');
		Route::delete('delete/{id?}', 'delete')->name('delete');
	});
});
	// Category
	Route::group(['prefix' => 'categories', 'as' => 'categories.'], function(){
		Route::controller(CategoryController::class)->group(function () {
			Route::get('', 'index')->name('index');
			Route::get('list', 'list')->name('list');
			Route::post('save/{id?}', 'save')->name('save');
			Route::get('find/{id?}', 'find')->name('find');
			Route::delete('delete/{id?}', 'delete')->name('delete');
		});
	});

	


	//product
	Route::group(['prefix' => 'products', 'as' => 'products.'], function(){
		Route::controller(ProductController::class)->group(function () {
			Route::get('', 'index')->name('index');
			Route::get('list', 'list')->name('list');
			Route::get('add', 'add')->name('add');
			Route::get('edit/{id?}', 'edit')->name('edit');
			Route::post('save/{id?}', 'save')->name('save');
			Route::get('find/{id?}', 'find')->name('find');
			Route::delete('delete/{id?}', 'delete')->name('delete');
		});
	});

	// Material
	Route::group(['prefix' => 'materials', 'as' => 'materials.'], function(){
		Route::controller(MaterialController::class)->group(function () {
			Route::get('', 'index')->name('index');
			Route::get('list', 'list')->name('list');
			Route::post('save/{id?}', 'save')->name('save');
			Route::get('find/{id?}', 'find')->name('find');
			Route::delete('delete/{id?}', 'delete')->name('delete');
		});
	});

	//supplier
	Route::group(['prefix' => 'suppliers', 'as' => 'suppliers.'], function(){
		Route::controller(SupplierController::class)->group(function () {
			Route::get('', 'index')->name('index');
			Route::get('list', 'list')->name('list');
			Route::post('save/{id?}', 'save')->name('save');
			Route::get('find/{id?}', 'find')->name('find');
			Route::delete('delete/{id?}', 'delete')->name('delete');
		});
	});


	//customer
	Route::group(['prefix' => 'customers', 'as' => 'customers.'], function(){
		Route::controller(CustomerController::class)->group(function () {
			Route::get('', 'index')->name('index');
			Route::get('list', 'list')->name('list');
			Route::post('save/{id?}', 'save')->name('save');
			Route::get('find/{id?}', 'find')->name('find');
			Route::delete('delete/{id?}', 'delete')->name('delete');
		});
	});

	//orders
	Route::group(['prefix' => 'orders', 'as' => 'orders.'], function(){
		Route::controller(OrderController::class)->group(function () {
			Route::get('', 'index')->name('index');
			Route::post('items', 'getItemFromCode')->name('get.items');
			Route::get('list', 'list')->name('list');
			Route::get('add', 'add')->name('add');
			Route::get('edit/{id?}', 'edit')->name('edit');
			Route::post('save/{id?}', 'save')->name('save');
			Route::get('find/{id?}', 'find')->name('find');
			Route::delete('delete/{id?}', 'delete')->name('delete');
			Route::post('payment', 'payment')->name('payment');
		});
	});

	// Stocks

	Route::group(['prefix' => 'stocks', 'as' => 'stocks.'], function(){
		Route::controller(StockController::class)->group(function () {
			Route::get('{type?}', 'index')->name('index');
			Route::get('list/{type?}', 'list')->name('list');
			Route::post('save/{stock_id?}', 'save')->name('save');
			Route::get('find/{stock_id?}', 'find')->name('find');
			Route::get('find-stocks/{id?}/{type?}', 'findItems')->name('find.items');
			Route::get('find-stocks-code/{code?}/{type?}', 'findItemsCode')->name('find.items.code');
			Route::delete('delete/{stock_id?}', 'delete')->name('delete');
		});
	});

	//activity logs
	Route::group(['prefix' => 'logs', 'as' => 'logs.'], function(){
		Route::controller(LogController::class)->group(function () {
			Route::get('', 'index')->name('index');
			Route::get('list', 'list')->name('list');
		});
	});

	//activity logs
	Route::group(['prefix' => 'support', 'as' => 'support.'], function(){
		Route::controller(SupportController::class)->group(function () {
			Route::get('', 'index')->name('index');
			Route::get('list', 'list')->name('list');
		});
	});


});


/* Put it at the top */

app/Models/Product.php
<?php
namespace App\Models;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use DNS1D;
class Product extends Model
{
	use HasFactory;

	protected $fillable = [
		'image',
		'product_code',
		'product_name',
		'description',
		'qty',
		'alert_qty',
		'price',
	];

	protected $appends = ['logo'];

	public function getLogoAttribute(){
		if (!empty($this->image)) {
			return asset('products/'.$this->image);
		}else{
			return asset('img/default.jpg');
		}
	}

	public function product_details(){
		return $this->hasMany('App\Models\ProductDetail', 'product_id', 'id');
	}

	public function stock_flow(){
		return $this->hasMany('App\Models\Stock', 'product_id', 'id');
	}

}

app/Http/Controllers/ProductController.php
<?php
namespace App\Http\Controllers;
use Illuminate\Http\Request;
use App\Models\Product;
use App\Models\ProductDetail;
use App\Models\Material;
use Validator;
use Str;
use Auth;

class ProductController extends Controller
{
	public function index(){
		return view('Product.index');
	}

	public function list(){
		$products = Product::whereNull('deleted_at')->get();
		return response()->json(['status' => true, 'data' => $products ]);
	}

	public function save(Request $request, $id = ""){
		$user_id = Auth::user()->id;										
		$rule2 = [];

		$rules = [
			'product_code' => 'required|unique:products,product_code,'.$id,
			'product_name' => 'required',
			'alert_qty' => 'required|numeric|min:1',
			'price' => 'required',
		];

		$rule2 = $this->validationProductDetails($request->get('details'));
		$validation_rules = array_merge($rules, $rule2['validation']);
		$validator = Validator::make($request->all(), $validation_rules, $rule2['rules']);

		if($validator->fails()){
			return response()->json(['status' => false, 'error' => $validator->errors() ]);
		}else{
			$data = [
				'product_code' => $request->get('product_code'),
				'product_name' => $request->get('product_name'),
				'description' => $request->get('description'),
				'price' => $request->get('price'),
				'alert_qty' => $request->get('alert_qty')
			];

			if ($request->has('image')) {
				$data['image'] = $request->file('image')->store('', 'products');
			}

			if(!empty($id)){
				$products = Product::where('id', $id)->update($data);
				if($products){
					makeLog($user_id, 'Updated Product', 'Updated Product named '.$request->product_name.' with the ID:'.$id);
					$this->saveProductDetails($request->get('details'), $id);
					return response()->json(['status' => true, 'message' => 'products saved successfully!']);
				}
			}else{
				$products = Product::create($data);
				if($products){
					makeLog($user_id, 'Added Product', 'Added Product named '.$request->product_name.' with the ID:'.$products->id);
					$this->saveProductDetails($request->get('details'), $products->id);
					return response()->json(['status' => true, 'message' => 'products updated successfully!']);
					// return response()->json(['status' => false, 'data' => $products->id]);
				}
			}
		}
	}


	public function validationProductDetails($details){
		$datas = [];
		$message_rules = [];

		if (!empty($details)) {
			foreach ($details as $key => $data) {
				if (empty($data['qty'])) {
					$datas['qty_'.$key] = 'required';
					$message_rules['qty_'.$key.'.required'] = 'The qty fields is required.';
				}

				if (empty($data['material_id'])) {
					$datas['material_id_'.$key] = 'required';
					$message_rules['material_id_'.$key.'.required'] = 'The material fields is required.';
				}
			}
		}

		return ['validation' => $datas, 'rules' => $message_rules];
	}

	public function saveProductDetails($details, $id){
		$clear = ProductDetail::where('product_id', $id)->delete();
		$counter = 0;
		foreach ($details as $key => $data) {
			ProductDetail::create(['product_id' => $id, 'material_id' => $data['material_id'], 'qty' => $data['qty']]);
			$counter++;
		}
		
		return $counter;
	}

	public function edit($id){
		$title = 'Edit Products';
		$products = Product::with(['product_details'])->findOrFail($id);		
		$materials = Material::get();
		return view('Product.add', compact('products', 'title', 'materials'));
	}

	public function add(){
		$title = 'Add Products';
		$materials = Material::get();
		return view('Product.add', compact('title', 'materials'));
	}

	public function find($id){
		$products = Product::findOrFail($id);
		return response()->json(['status' => true, 'data' => $products ]);
	}

	public function delete($id){
		$user_id = Auth::user()->id;										
		$products = Product::findOrFail($id);
		$products->deleted_at = now();
		if($products->save()){
			makeLog($user_id, 'Deleted Product', 'Deleted Product named '.$products->product_name.' with the ID:'.$id);
			return response()->json(['status' => true, 'message' => 'Record deleted successfully!' ]);
		}
	}

}

resources/views/Product/add.blade.php
@extends('Layout.admin_app')
@section('title', $title)
@section('css')
<style type="text/css">
	.img-container {
	  position: relative;
	  width: 50%;
	}

	.img-image {
	  opacity: 1;
	  display: block;
	  width: 100%;
	  height: auto;
	  transition: .5s ease;
	  backface-visibility: hidden;
	}

	.middle {
	  transition: .5s ease;
	  opacity: 0;
	  position: absolute;
	  top: 50%;
	  left: 50%;
	  transform: translate(-50%, -50%);
	  -ms-transform: translate(-50%, -50%);
	  text-align: center;
	}

	.img-container:hover .img-image {
	  opacity: 0.3;
	}

	.img-container:hover .middle {
	  opacity: 1;
	}

	.img-text {
/*	  background-color: #04AA6D;
	  color: white;
	  font-size: 16px;
	  padding: 16px 32px;*/
	}
</style>
@endsection
@section('content')
<div class="container-fluid pt-3">
	<div class="row">
		<div class="col-md-12"><h1>{{ $title }}</h2></div>
		<div class="col-md-12">
			<form class="needs-validation" id="product_form" action="{{ route('products.save') }}/{{ $products->id ?? '' }}" novalidate>
				<div class="row">
					<input type="hidden" name="id" id="id" value="{{ $products->id ?? '' }}"/>
					<div class="col-md-8">
						<div class="card">
							<div class="card-header">Product Details</div>
							<div class="card-body">
								<div class="row">
									<div class="col-md-6">
										<label>Product code</label>
										<input type="text" name="product_code" id="product_code" class="form-control form-control" required value="{{ $products->product_code ?? '' }}"/>
									</div>
									<div class="col-md-6">
										<label>Stock Alert <small class="text-info"><b> The System will alert you if the stocks is less than/qual to this value.</b></small></label>
										<input type="number" name="alert_qty" id="alert_qty" class="form-control form-control" required value="{{ $products->alert_qty ?? '' }}"/>
									</div>
									<div class="col-md-12">
										<label>Product name</label>
										<input type="text" name="product_name" id="product_name" class="form-control form-control" required value="{{ $products->product_name ?? '' }}"/>
									</div>
									<div class="col-md-12">
										<label>Product Description</label>
										<textarea name="description" id="description" class="form-control form-control">{{ $products->description ?? '' }}</textarea>
									</div>
								</div>
							</div>
						</div>

						<div class="card">
							<div class="card-header">Raw Materials</div>
							<div class="card-body">
								<table class="table table-bordered">
									<thead>
										<tr>
											<th>Material Name</th>
											<th>Kg</th>
											<th class="text-center">Price/KG</th>
											<th class="text-center">Options</th>
										</tr>
									</thead>
									<tbody id="raw_materials_item">
									</tbody>
								</table>

								<div class="text-right mt-5">
									<button class="btn btn-primary" type="button" onclick="add_item();"><i class="fa fa-plus"></i> Add Items</button>
								</div>
							</div>
						</div>
					</div>
					<div class="col-md-4">
						<div class="card">
							<div class="card-header">Product Image</div>
							<div class="card-body">
								<div class="text-center">
									<input type="file" name="image" id="image" onchange="previewImg(this, 'product_image_preview');" class="d-none form-control">
									<center>
										<div class="img-container">
											<img src=" {{ (!empty($products->image))? asset('products/'.$products->image) :  asset('img/default.jpg') }}" alt="product-image" id="product_image_preview" class="img-fluid img-image">
										  <div class="middle">
										    <button class="btn btn-primary" type="button" onclick="$('#image').click();">Upload Image</button>
										  </div>
										</div>
									</center>
								</div>	
							</div>
						</div>
						<div class="card">
							<div class="card-header">Pricing</div>
							<div class="card-body">
								<div class="col-md-12 mb-3">
									<label>Suggested Price <small class="text-info">This price is based on the material's price.</small></label>
									<div class="input-group mb-3">
										 <div class="input-group-prepend">
										    <span class="input-group-text" id="basic-addon1">₱</span>
										  </div>
  										<input type="text" name="suggested_price" id="suggested_price" class="form-control form-control form-control-lg bg-white" placeholder="0" aria-label="Recipient's username" aria-describedby="button-addon2" readonly />
									  	<button class="btn btn-outline-success rounded-0" type="button" onclick="$('#price').val($('#suggested_price').val());" id="button-addon2">Use Price</button>
									</div>
								</div>
								<div class="col-md-12 mb-3">
									<label>Price</label>
									<div class="input-group">
										<div class="input-group-prepend">
										   <span class="input-group-text" id="basic-addon1">₱</span>
										 </div>
										<input type="text" name="price" id="price" class="form-control form-control form-control-lg" placeholder="0" required value="{{ $products->price ?? '' }}"/>
									</div>
								</div>
							</div>
						</div>
						<div class="row">
							<div class="col-md-6">
								<a href="{{ route('products.index') }}" class="btn btn-dark btn-block" type="button">Cancel</a>
							</div>
							<div class="col-md-6">
								<button class="btn btn-success btn-block" id="product_form_btn" type="submit">Save</button>
							</div>
						</div>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>


@endsection
@section('script')
<script type="text/javascript">
var default_value = '{!! $products->product_details ?? '' !!}';

renderData(default_value);


function renderData(default_value){
	if (default_value == '') {

	}else{
		let data = JSON.parse(default_value);
		data.map(function(dt){
			add_item(dt.material_id, dt.qty, dt.price);
		});
	}
}


var counter = 0;
function add_item(material_id = '', qty = '', price = 0){
	let output = '';
	output += '<tr id="item_'+counter+'">';
	output += '<td width="300">';
	output += '<select name="details['+counter+'][material_id]" id="material_id_'+counter+'" value="'+material_id+'" oninput="get_selected_data('+counter+')" class="form-control materials"></select>';
	output += '</td>';
	output += '<td><input type="number" name="details['+counter+'][qty]" id="qty_'+counter+'" value="'+qty+'" placeholder="0" oninput="get_total_price_from_materials();" class="form-control"></td>';
	output += '<td class="text-center item_price" data-id="'+counter+'" id="price_'+counter+'">'+0+'</td>';
	output += '<td class="text-center"><button class="btn btn-danger" onclick="remove_item('+counter+');" type="button"><i class="fa fa-times"></i></button></td>';
	output += '</tr>';
	$("#raw_materials_item").append(output);
	render_option('material_id_'+counter, material_id);
	get_selected_data(counter);
	get_total_price_from_materials();
	counter++;

}


function render_option(element, selected = ''){
	let data = JSON.parse('@json($materials)');
	
	 let output ='<option value="" selected>Select Material</option>';
	 output += data.map(function(dt){
		let out = '';
		out += '<option value="'+dt.id+'" data-price="'+dt.price_per_kilo+'">'+dt.material_name+'</option>';
		return out;
	}).join('');

	$("#"+element).html(output);
	$("#"+element).val(selected);
}


function get_selected_data(counter){
	let price = $("#material_id_"+counter).find(':selected').data('price');
	$("#price_"+counter).text(price);

	get_total_price_from_materials();
}

function get_total_price_from_materials(){
	var total = 0;
	$(".item_price").each(function(e){
		let id = $(this).data('id');
		let num = Number($(this).text());
		let qty = Number($("#qty_"+id).val());
		total += (qty * num);
	});

	$("#suggested_price").val(total);
}

function remove_item(counter){
  var url = '';
  swal({
        title: "Are you sure?",
        text: "Do you want to remove this item?",
        type: "warning",
        showCancelButton: true,
        confirmButtonColor: "#DD6B55",
        confirmButtonText: "Yes",
        closeOnConfirm: true
      },
        function(){
      		$("#item_"+counter).remove();
			get_total_price_from_materials();
      });
  }


$('#product_form').on('submit', function(e){
  e.preventDefault();
  let form = $("#product_form")[0];
  var data = new FormData(form);
  let url = $(this).attr('action');
  $.ajax({
      type:"POST",
      url:url,
      data:data,
      enctype: 'multipart/form-data',
      processData: false,  // Important!
      contentType: false,
      dataType:'json',
      beforeSend:function(){
		$('#product_form_btn').prop('disabled', true);
      },
      success:function(response){
         console.log(response);
  		if (response.status == true) {
			swal("Success", response.message, "success");
			setTimeout(function(){
				window.location = "{{ route('products.index') }}";
			}, 1500);
		}else{
			console.log(response);
		}
		validation('product_form', response.error);
		$('#product_form_btn').prop('disabled', false);
      },
      error: function(error){
        console.log(error);
      }
    });
});
</script>
@endsection

resources/views/Product/index.blade.php
@extends('Layout.admin_app')
@section('title', 'Products')
@section('content')
<div class="container-fluid pt-3">
	<div class="row mb-3">
		<div class="col-md-6 text-capitalize"><h1>Products Management</h2></div>
		<div class="col-md-6 text-right">
			<a href="{{ route('products.add') }}" class="btn btn-primary">Add Products</a>
			<button type="button" onclick="$('.btn_print').click();" class="btn btn-info"><i class="fa fa-print"></i> Print</button>
			<button type="button" onclick="$('.excelButton').click();" class="btn btn-success"><i class="fa fa-file-excel"></i> Export Excel</button>
		</div>
		<div class="col-md-12">
			<table class="table table-bordered table-striped" id="tbl_products" style="width: 100%;"></table>
		</div>
	</div>
</div>
@include('StockFlow.modal')
@endsection

@section('script')
@include('StockFlow.script')
<script type="text/javascript">
var tbl_products;
show_products();
function show_products(){
	if(tbl_products){
		tbl_products.destroy();
	}
	tbl_products = $('#tbl_products').DataTable({
		dom: 'Bfrtip',
        buttons: [
            {extend : 'print', 
            className: 'btn_print d-none',
             customize: function ( win ) {
                    $(win.document.body)
                        .css( 'font-size', '10pt' )
                        .prepend(
                            '<center><img src="{{ asset('img/logo.png') }}"/><div class="h3">Ace Plastic</div></center>'
                        );
                },
                exportOptions: {
                        stripHtml : false,
                        columns: [0, 2, 3, 4]
                }
		},
            { 
            	extend: 'excel', 
           		className: 'excelButton d-none',
           		exportOptions: {
                        columns: [0, 2, 3, 4]
                } 
            }
        ],
		destroy: true,
		pageLength: 10,
		responsive: true,
		ajax: "{{ route('products.list') }}",
		deferRender: true,
		columns: [
			{
				className: 'd-none',
				"data": 'product_code',
				"title": 'Barcode',
			},{
				width: 90,
				className: 'text-center hide-print',
				"data": 'product_code',
				"title": 'Barcode',
				"render":function(data, type, row, meta){
					return '<svg class="qrcodes d-none" id="qrcode_'+data+'" data-value="'+data+'"></svg> <img id="img_qrcode_'+data+'">';

				}
			},
			{
				className: '',
				"data": 'product_name',
				"title": 'Product name',
			},
			{
				className: 'text-center',
				"data": 'qty',
				"title": 'QTY',
				"render":function(data, type, row, meta){
					if(data == '' || data == 0 || data == null){
						return '0';
					}else{
						return data;
					}
				}
			},
			{
				className: 'text-right',
				"data": 'price',
				"title": 'Price',
				"render": function(data){
					return money.format(data);
				}
			},
			{
				className: 'width-option-1 text-center hide-print',
				width: '15%',
				"data": 'id',
				"orderable": false,
				"title": 'Options',
				"render": function(data, type, row, meta){
					newdata = '';
					newdata += '<a href="{{ route('products.edit') }}/'+row.id+'" class="btn btn-success btn-sm font-base mt-1" ><i class="fa fa-edit"></i></a> ';
					newdata += ' <button class="btn btn-danger btn-sm font-base mt-1" onclick="delete_products('+row.id+');" type="button"><i class="fa fa-trash"></i></button>';
					newdata += ' <button class="btn btn-primary btn-sm font-base mt-1"  onclick="add_stocks('+row.id+', \'products\', \''+row.product_name+'\', \'#'+row.product_code+'\')" type="button"><i class="fas fa-box-tissue"></i></button>';
					return newdata;
				}
			}
		]
	});

	setTimeout(function(){
		qrcodeRender();
	},1500);
}




function delete_products(id){
	swal({
		title: "Are you sure?",
		text: "Do you want to delete products?",
		type: "warning",
		showCancelButton: true,
		confirmButtonColor: "#DD6B55",
		confirmButtonText: "Yes",
		closeOnConfirm: false
	},
	function(){
		$.ajax({
			type:"DELETE",
			url:"{{ route('products.delete') }}/"+id,
			data:{},
			dataType:'json',
			beforeSend:function(){
		},
		success:function(response){
			// console.log(response);
			if (response.status == true) {
				show_products();
				swal("Success", response.message, "success");
			}else{
				console.log(response);
			}
		},
		error: function(error){
			console.log(error);
		}
		});
	});
}
</script>
@endsection