routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\AccountController;
use App\Http\Controllers\BrandController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\MaterialController;
use App\Http\Controllers\SupplierController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\UserAccountController;
use App\Http\Controllers\StockController;
use App\Http\Controllers\LogController;
use App\Http\Controllers\SupportController;

 
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () {
    return view('Auth.index');
})->name('login');




//Authentications/Login
Route::group(['prefix'=> 'auth', 'as' => 'auth.'], function(){
	// For Login
	Route::controller(AuthController::class)->group(function () {
 		 Route::post('request', 'authenticate')->name('authenticate');
	});
});


Route::group(['prefix' => 'user_accounts', 'as' => 'user_accounts.'], function(){
	Route::controller(UserAccountController::class)->group(function () {
		Route::get('', 'index')->name('index');
		Route::get('list', 'list')->name('list');
		Route::post('save/{id?}', 'save')->name('save');
		Route::get('find/{id?}', 'find')->name('find');
		Route::get('toggle/{id?}/{status?}', 'toggle')->name('toggle');
	});
});


Route::group(['middleware' => ['auth']], function(){
    Route::get('logout', [AuthController::class, 'logout'])->name('logout');

    // Dashboard
    Route::get('dashboard', [DashboardController::class, 'index'])->name('dashboard');
 


	// Brands
Route::group(['prefix' => 'brands', 'as' => 'brands.'], function(){
	Route::controller(BrandController::class)->group(function () {
		Route::get('', 'index')->name('index');
		Route::get('list', 'list')->name('list');
		Route::post('save/{id?}', 'save')->name('save');
		Route::get('find/{id?}', 'find')->name('find');
		Route::delete('delete/{id?}', 'delete')->name('delete');
	});
});
	// Category
	Route::group(['prefix' => 'categories', 'as' => 'categories.'], function(){
		Route::controller(CategoryController::class)->group(function () {
			Route::get('', 'index')->name('index');
			Route::get('list', 'list')->name('list');
			Route::post('save/{id?}', 'save')->name('save');
			Route::get('find/{id?}', 'find')->name('find');
			Route::delete('delete/{id?}', 'delete')->name('delete');
		});
	});

	


	//product
	Route::group(['prefix' => 'products', 'as' => 'products.'], function(){
		Route::controller(ProductController::class)->group(function () {
			Route::get('', 'index')->name('index');
			Route::get('list', 'list')->name('list');
			Route::get('add', 'add')->name('add');
			Route::get('edit/{id?}', 'edit')->name('edit');
			Route::post('save/{id?}', 'save')->name('save');
			Route::get('find/{id?}', 'find')->name('find');
			Route::delete('delete/{id?}', 'delete')->name('delete');
		});
	});

	// Material
	Route::group(['prefix' => 'materials', 'as' => 'materials.'], function(){
		Route::controller(MaterialController::class)->group(function () {
			Route::get('', 'index')->name('index');
			Route::get('list', 'list')->name('list');
			Route::post('save/{id?}', 'save')->name('save');
			Route::get('find/{id?}', 'find')->name('find');
			Route::delete('delete/{id?}', 'delete')->name('delete');
		});
	});

	//supplier
	Route::group(['prefix' => 'suppliers', 'as' => 'suppliers.'], function(){
		Route::controller(SupplierController::class)->group(function () {
			Route::get('', 'index')->name('index');
			Route::get('list', 'list')->name('list');
			Route::post('save/{id?}', 'save')->name('save');
			Route::get('find/{id?}', 'find')->name('find');
			Route::delete('delete/{id?}', 'delete')->name('delete');
		});
	});


	//customer
	Route::group(['prefix' => 'customers', 'as' => 'customers.'], function(){
		Route::controller(CustomerController::class)->group(function () {
			Route::get('', 'index')->name('index');
			Route::get('list', 'list')->name('list');
			Route::post('save/{id?}', 'save')->name('save');
			Route::get('find/{id?}', 'find')->name('find');
			Route::delete('delete/{id?}', 'delete')->name('delete');
		});
	});

	//orders
	Route::group(['prefix' => 'orders', 'as' => 'orders.'], function(){
		Route::controller(OrderController::class)->group(function () {
			Route::get('', 'index')->name('index');
			Route::post('items', 'getItemFromCode')->name('get.items');
			Route::get('list', 'list')->name('list');
			Route::get('add', 'add')->name('add');
			Route::get('edit/{id?}', 'edit')->name('edit');
			Route::post('save/{id?}', 'save')->name('save');
			Route::get('find/{id?}', 'find')->name('find');
			Route::delete('delete/{id?}', 'delete')->name('delete');
			Route::post('payment', 'payment')->name('payment');
		});
	});

	// Stocks

	Route::group(['prefix' => 'stocks', 'as' => 'stocks.'], function(){
		Route::controller(StockController::class)->group(function () {
			Route::get('{type?}', 'index')->name('index');
			Route::get('list/{type?}', 'list')->name('list');
			Route::post('save/{stock_id?}', 'save')->name('save');
			Route::get('find/{stock_id?}', 'find')->name('find');
			Route::get('find-stocks/{id?}/{type?}', 'findItems')->name('find.items');
			Route::get('find-stocks-code/{code?}/{type?}', 'findItemsCode')->name('find.items.code');
			Route::delete('delete/{stock_id?}', 'delete')->name('delete');
		});
	});

	//activity logs
	Route::group(['prefix' => 'logs', 'as' => 'logs.'], function(){
		Route::controller(LogController::class)->group(function () {
			Route::get('', 'index')->name('index');
			Route::get('list', 'list')->name('list');
		});
	});

	//activity logs
	Route::group(['prefix' => 'support', 'as' => 'support.'], function(){
		Route::controller(SupportController::class)->group(function () {
			Route::get('', 'index')->name('index');
			Route::get('list', 'list')->name('list');
		});
	});


});


/* Put it at the top */

app/Models/Order.php
<?php
namespace App\Models;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
	use HasFactory;

	protected $fillable = [
		'customer_id',
		'delivery_date',
		'status',
		'total_amount',
		'note',
		'user_id',
		'last_edited',
		'total_amount_receive',
		'amount_changed',
		'order_tracking_no'
	];


	public function customer(){
		return $this->belongsTo('App\Models\Customer', 'customer_id', 'id');
	}

	public function items(){
		return $this->hasMany('App\Models\OrderDetail', 'order_id', 'id');
	}

}

app/Http/Controllers/OrderController.php
<?php
namespace App\Http\Controllers;
use Illuminate\Http\Request;
use App\Models\Order;
use App\Models\OrderDetail;
use App\Models\Product;
use App\Models\Stock;
use Validator;
use Auth;

class OrderController extends Controller
{
	public function index(){
		return view('Order.index');
	}

	public function list(){
		$orders = Order::with(['customer'])->whereNull('deleted_at')->get();
		return response()->json(['status' => true, 'data' => $orders ]);
	}

	public function getItemFromCode(Request $request){
		$validator = Validator::make($request->all(), [
			'item_code' => 'required',
		]);

		if($validator->fails()){
			return response()->json(['status' => false, 'error' => $validator->errors() ]);
		}else{
			$product = Product::where('product_code', $request->get('item_code'));

			if ($product->count() > 0) {
				$product_details = $product->first();

				if ($product_details->qty > 0) {
					return response()->json(['status' => true, 'data' => $product_details]);
				}else{
					$validator->errors()->add('item_code', 'Insufficient stock!');
					return response()->json(['status' => false, 'error' => $validator->errors() ]);
				}

			}else{
				$validator->errors()->add('item_code', 'This Item is not registered to the system!');
				return response()->json(['status' => false, 'error' => $validator->errors() ]);
			}
		}
	}

	public function save(Request $request, $id = ""){
		$user_id = Auth::user()->id;										
		$validator = Validator::make($request->all(), [
			'customer' => 'required',
			'delivery_date' => 'required',
			'total_bill' => 'required'
		], [
			'total_bill.required' => 'Please add items to proceed!'
		]);

		if($validator->fails()){
			return response()->json(['status' => false, 'error' => $validator->errors() ]);
		}else{
			// return response()->json(['status' => false, 'data' => $request->all()]);
			if(!empty($id)){
				$orders = Order::where('id', $id)->update([
					'customer_id' => $request->get('customer'),
					'delivery_date' => $request->get('delivery_date'),
					'total_amount' => $request->get('total_bill'),
				]);
				if($orders){
					makeLog($user_id, 'Updated Order', 'Updated Order with the ID:'.$id);
					$this->saveOrderDetails($request->get('items'), $id);
					return response()->json(['status' => true, 'message' => 'orders saved successfully!']);
				}
			}else{
				$orders = Order::create([
					'customer_id' => $request->get('customer'),
					'delivery_date' => $request->get('delivery_date'),
					'order_tracking_no' => getOrderSlug(),
					'status' => 0,
					'total_amount' => $request->get('total_bill'),

				]);
				if($orders){
					makeLog($user_id, 'Added Order', 'Added Order with the ID:'.$orders->id);
					$this->saveOrderDetails($request->get('items'), $orders->id);
					return response()->json(['status' => true, 'message' => 'orders updated successfully!']);
				}
			}
		}
	}

	public function payment(Request $request){
		$user_id = Auth::user()->id;										
		$validator = Validator::make($request->all(), [
				'bill' => 'required',
				'order_id' => 'required',
				'amount_tendered' => 'required|numeric|min:'.$request->bill,
		]);

		if($validator->fails()){
			return response()->json(['status' => false, 'error' => $validator->errors() ]);
		}else{
			$check_stock_deduction = $this->deductProduct($request->get('order_id'));

			if ($check_stock_deduction['error'] > 0) {
					return response()->json(['status' => false, 'message' => 'Cannot process your payment please check stocks.']);
			}else{
				$order = Order::where('id', $request->get('order_id'))->update([
					'total_amount' => $request->get('bill'),
					'amount_tendered' => $request->get('amount_tendered'),
					'amount_changed' => $request->get('change'),
					'status' => 1,
				]);

				if ($order) {
					return response()->json(['status' => true, 'message' => 'Payment processed successfully!']);
				}
			}
		}
	}

	public function deductProduct($id){
		$error = 0;
		$success = 0;
		$user_id = Auth::user()->id;

		$details = OrderDetail::where('order_id', $id)->get();
		foreach ($details as $detail) {
			$product_id =  $detail->product_id;
			$qty =  $detail->qty;
			$updated_qty = $this->updated_product($product_id, $qty);

			Product::where('id', $product_id)->update(['qty' => $updated_qty['updated_qty']]);

			$stocks = Stock::create([
						'product_id' => $product_id,
						'qty' => $qty,
						'status' => 'stock_out',
						'note' => 'Deducted for order ID:'. $product_id,
						'user_id' => $user_id,
						'qty_at_that_time' => $updated_qty['current_qty'],
						'updated_qty' => $updated_qty['updated_qty'],
					]);

			return ['error' => $error, 'success' => $success];
		}
	}

	public function updated_product($product_id, $qty){
			$product = Product::find($product_id);
			return ['updated_qty' => ($product->qty - $qty), 'current_qty' => $product->qty];
	}

	public function saveOrderDetails($details, $id){
		$clear = OrderDetail::where('order_id', $id)->delete();
		$counter = 0;
		foreach ($details as $key => $data) {
			OrderDetail::create(['order_id' => $id, 'product_id' => $data['id'], 'qty' => $data['qty'], 'price' => $data['price']]);
			$counter++;
		}
		
		return $counter;
	}


	public function edit($id){
		$title = 'Edit Order';
		$orders = Order::with(['items', 'items.products'])->findOrFail($id);
		return view('Order.add', compact('orders', 'title'));
	}

	public function add(){
		$title = 'Add Order';
		return view('Order.add', compact('title'));
	}

	public function find($id){
		$orders = Order::findOrFail($id);
		return response()->json(['status' => true, 'data' => $orders ]);
	}

	public function delete($id){
		$user_id = Auth::user()->id;												
		$orders = Order::findOrFail($id);
		$orders->deleted_at = now();
		if($orders->save()){
			makeLog($user_id, 'Deleted Order', 'Deleted Order with the ID:'.$orders->id);
			return response()->json(['status' => true, 'message' => 'Record deleted successfully!' ]);
		}
	}

}

resources/views/Order/add.blade.php
@extends('Layout.admin_app')
@section('title', $title)
@section('css')
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/css/select2.min.css" rel="stylesheet" />
@endsection
@section('content')
<div class="container-fluid pt-3">
	<div class="row">
		<div class="col-md-12"><h1>{{ $title }} <small class="float-right"><b>{{ (!empty( $orders->order_tracking_no))? $orders->order_tracking_no : '' }}</b></small></h2></div>
		<div class="col-md-12">
			<form class="needs-validation" id="item_form" action="{{ route('orders.get.items') }}" novalidate>
				<div class="row">
					<div class="col-md-12">
						<div class="form-group">
							<input type="text" class="form-control form-control-lg" id="item_code" name="item_code" placeholder="Type or Scan Item code">
						</div>
					</div>
				</div>
			</form>

			<form class="needs-validation" id="order_form" action="{{ route('orders.save') }}/{{ $orders->id ?? '' }}" novalidate>
				<div class="row">
					<input type="hidden" name="id" id="id" value="{{ $orders->id ?? '' }}"/>
					<div class="col-md-3">
						<div class="card">
							<div class="card-body">
								<div class="row">
									<div class="col-md-12 form-group">
										<label>Customer Name</label>
										<select name="customer" id="customer" class="form-control selection"  data-value="{{ $orders->customer_id ?? '' }}"  required {{ (!empty($orders->status) && $orders->status == 1)? 'disabled' : '' }}>
											<option value="" selected>Please Select Customer</option>
											@foreach(getCustomerOption() as $customer)
											<option value="{{ $customer->id }}">{{ $customer->customer_name }} - {{ $customer->contact_person }}</option>
											@endforeach
										</select>
									</div>
									<div class="col-md-12 form-group">
										<label>Order/Delivery Date</label>
										<input type="date" name="delivery_date" id="delivery_date" class="form-control " required value="{{ $orders->delivery_date ?? '' }}" {{ (!empty($orders->status) && $orders->status == 1)? 'disabled' : '' }}>
									</div>
								</div>
								<h4 class="text-right mt-3">Total Bill</h4>
								<h3 class="text-right" id="total_bill_text">₱{{ (!empty($orders->total_amount))? number_format($orders->total_amount, 2) : '0.00' }}</h3>
								<div class="form-group text-right">
									<input type="hidden" name="total_bill" id="total_bill" class="form-control" value="{{ $orders->total_amount ?? '' }}">
								</div>
									<button class="btn btn-primary btn-block {{ (!empty($orders->status) && $orders->status == 1)? 'd-none' : '' }}">Save Order</button>
							</div>
						</div>
					</div>
					<div class="col-md-9">
						<div class="card">
							<div class="card-header">Items</div>
							<div class="card-body">
								<table class="table table-bordered" style="width: 100%;">
									<thead>
										<tr>
											<th class="text-center" width="25">Item Code</th>
											<th class="text-center" width="220">Item Name</th>
											<th class="text-center" width="25">Price</th>
											<th width="25" class="text-center">Qty</th>
											<th width="15" class="text-center">Actions</th>
										</tr>
									</thead>
									<tbody id="order_items">
										
									</tbody>
								</table>
							</div>
						</div>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>



@endsection


@section('script')
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/js/select2.min.js"></script>
<script>
var products = [];
var default_value = '{!! $orders->items ?? '' !!}';

renderData(default_value);

function renderData(default_value){
	if (default_value == '') {

	}else{
		let data = JSON.parse(default_value);
		data.map(function(dt){
			append_items(dt.product_id, dt.products.product_code, dt.products.product_name, dt.price, dt.stock, dt.qty);
		});
	}
}


$("#item_form").on('submit', function(e){
	e.preventDefault();
	let url = $(this).attr('action');
	let formData = $(this).serialize();
	$.ajax({
		type:"POST",
		url:url,
		data:formData,
		dataType:'json',
		beforeSend:function(){
		},
		success:function(response){
			console.log(response);
			if (response.status == true) {
				append_items(response.data.id, response.data.product_code, response.data.product_name, response.data.price, response.data.qty, 1);	
				$("#item_code").val('');
				$("#item_code").focus();
			}
			validation('item_form', response.error);
		},
		error: function(error){
			console.log(error);
		}
	});
});


function append_items(id, item_code, name, price, stock, qty){
	let new_qty = qty;
	let output = '';

	if (id in products) {
		new_qty = (Number(qty) + Number(products[id]));		
	}

	if (new_qty > stock) {
		swal("Error", "The product stock(s) is only "+stock+" left.\n Replenish this product to be able to continue.", "error");
	}else{
		if (id in products) {
			$("#item_qty_"+id).val(new_qty);
		}else{
			output +='<tr class="cart_items" id="cart_item_'+id+'" data-id="'+id+'" data-price="'+price+'" data-stock="'+stock+'">';
			output +='<td  class="text-center">'+item_code+'<input type="hidden" name="items['+id+'][price]" value="'+price+'" class="form-control"></td>';
			output +='<td  class="text-center">'+name+'</td>';
			output +='<td  class="text-center">'+money.format(price)+'</td>';
			output +='<td  class="text-center"><input type="hidden" name="items['+id+'][id]" value="'+id+'" class="form-control"><input type="number" name="items['+id+'][qty]" id="item_qty_'+id+'" oninput="return edit_qty('+id+')" value="'+new_qty+'" class="form-control text-center"></td>';

			@if(!empty($orders->status) && $orders->status == 1)
				output +='<td class="text-center"><button class="btn btn-danger"  type="button" disabled><i class="fa fa-times"></i></button></td>';
			@else
				output +='<td class="text-center"><button class="btn btn-danger"  type="button" onclick="remove_cart('+id+');"><i class="fa fa-times"></i></button></td>';
			@endif
			output +='</tr>';

			$("#order_items").append(output);
		}
		products[id] = new_qty;
		get_all_items();
	}
}


function edit_qty(id){
	let qty = $("#item_qty_"+id).val();
	let stock = $("#cart_item_"+id).data('stock');

	if (Number(qty) > Number(stock)) {
		 $("#item_qty_"+id).val(stock);
	}else if(Number(qty) < 1){
		 $("#item_qty_"+id).val(1);
	}else{
		get_all_items();
	}
}

function get_all_items(){
	products = [];
	let total = 0;
	$(".cart_items").each(function(e){
		let id = $(this).data('id');
		let price = $(this).data('price');
		let qty = $("#item_qty_"+id).val();
		products[id] = qty;
		total += (Number(qty) * Number(price));
	});

	$("#total_bill").val(total);
	$("#total_bill_text").text(money.format(total));
}



function remove_cart(id){
  swal({
        title: "Are you sure?",
        text: "Do you want to remove this item?",
        type: "warning",
        showCancelButton: true,
        confirmButtonColor: "#DD6B55",
        confirmButtonText: "Yes",
        closeOnConfirm: true
      },
        function(){
         $("#cart_item_"+id).remove();
         get_all_items();
      });
  }

$("#order_form").on('submit', function(e){
	e.preventDefault();
	let url = $(this).attr('action');
	let formData = $(this).serialize();
	$.ajax({
		type:"POST",
		url:url,
		data:formData,
		dataType:'json',
		beforeSend:function(){
			$('#order_form_btn').prop('disabled', true);
		},
		success:function(response){
			// console.log(response);
			if (response.status == true) {
				swal("Success", response.message, "success");
				setTimeout(function(){
					window.location = "{{ route('orders.index') }}";
				}, 1500);
			}else{
				console.log(response);
			}
				validation('order_form', response.error);
				$('#order_form_btn').prop('disabled', false);
		},
		error: function(error){
			$('#order_form_btn').prop('disabled', false);
			console.log(error);
		}
	});
});

$(".selection").each(function(e){
	let selected = $(this).data('value');
	$(this).val(selected);
});
</script>
@endsection

resources/views/Order/index.blade.php
@extends('Layout.admin_app')
@section('title', 'Orders')
@section('content')
<div class="container-fluid pt-3">
	<div class="row mb-3">
		<div class="col-md-6 text-capitalize"><h1>Orders Management</h2></div>
		<div class="col-md-6 text-right">
			<a href="{{ route('orders.add') }}" class="btn btn-primary">Add Orders</a>
			<button type="button" onclick="$('.btn_print').click();" class="btn btn-info"><i class="fa fa-print"></i> Print</button>
			<button type="button" onclick="$('.excelButton').click();" class="btn btn-success"><i class="fa fa-file-excel"></i> Export Excel</button>
		</div>
		<div class="col-md-12">
			<table class="table table-bordered table-striped" id="tbl_orders" style="width: 100%;"></table>
		</div>
	</div>
</div>

<form class="needs-validation" id="payment_order_form" action="{{ route('orders.payment') }}" novalidate="">
<div class="modal fade" role="dialog" id="payment_modal">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<div class="modal-title">
					Add Payment
				</div>
				<button class="close" data-dismiss="modal">&times;</button>
			</div>
			<div class="modal-body">
				<div class="row">
					<div class="col-md-12">
						<div class="card bg-success text-white">
							<div class="card-body">
								<label id="order_no">Order#123123</label><br>
								<label>Total Bill</label>
								<h1 class="m-1 bg-success" id="bill_text">P 0.00</h1>
							</div>
						</div>
						<input type="hidden" name="bill" id="bill" class="form-control form-control-lg" required/>
						<input type="hidden" name="order_id" id="order_id"/>
					</div>
					<div class="col-md-12">
						<div class="card bg-primary text-white">
							<div class="card-body">
								<label>Change </label>
								<h1 class="m-1" id="change_text">P 0.00</h1>
							</div>
						</div>
						<input type="hidden" name="change" id="change" class="form-control form-control-lg" value="0" required disabled="" />
					</div>
					<div class="col-md-12 mb-3">
						<label>Amount Tendered </label>
						<input type="number" name="amount_tendered" id="amount_tendered" oninput="enter_payment(this.value);" class="form-control form-control-lg" placeholder="0" required/>
					</div>
					<div class="col-md-12 form-group">
						<button class="btn btn-primary btn-block" type="submit">Process Payment</button>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
</form>

@endsection


@section('script')
<!-- Javascript Function-->
<script>
function enter_payment(value){
	let bill = $("#bill").val();
	let total_amount = Number(value) - Number(bill);
	
	if (isNaN(total_amount)) {
		$("#change").val(0);
		$("#change_text").text('₱0.00');
	}else{
		$("#change_text").text(money.format(total_amount));
		$("#change").val(total_amount);
	}
}

$("#payment_order_form").on('submit', function(e){
    e.preventDefault();
    let url = $(this).attr('action');
    let data = $(this).serialize();
    $.ajax({
        type:"POST",
        url:url,
        data:data,
        dataType:'json',
        beforeSend:function(){
        },
        success:function(response){
         	console.log(response);
             if (response.status == true) {
             	swal("Success", response.message, 'success');
				$("#payment_modal").modal('hide');
				show_orders();
             }

			validation('payment_order_form', response.error);

        },
        error: function(error){
          console.log(error);
        }
      });
});


function add_payment(order_id, order_tracking_no, bill){
	$("#order_id").val(order_id);
	$("#order_tracking_no").text(order_tracking_no);
	$("#bill").val(bill);
	$("#bill_text").text(money.format(bill));
	$("#payment_modal").modal('show');
}

var tbl_orders;
show_orders();
function show_orders(){
	if(tbl_orders){
		tbl_orders.destroy();
	}
	tbl_orders = $('#tbl_orders').DataTable({
		dom: 'Bfrtip',
        buttons: [
            {extend : 'print', 
            className: 'btn_print d-none',
             customize: function ( win ) {
                    $(win.document.body)
                        .css( 'font-size', '10pt' )
                        .prepend(
                            '<center><img src="{{ asset('img/logo.png') }}"/><div class="h3">Ace Plastic</div></center>'
                        );
                },
                exportOptions: {
                        stripHtml : true,
                        columns: [0, 1, 2, 3]
                }
		},
            { 
            	extend: 'excel', 
           		className: 'excelButton d-none',
           		exportOptions: {
                        columns: [0, 1, 2, 3]
                } 
            }
        ],
		destroy: true,
		pageLength: 10,
		responsive: true,
		ajax: "{{ route('orders.list') }}",
		deferRender: true,
		columns: [
			{
				className: '',
				"data": 'order_tracking_no',
				"title": 'Order No',
			},
			{
				className: '',
				"data": 'customer_id',
				"title": 'Customer',
				"render":function(data, type, row, meta){
					return row.customer.customer_name+' '+row.customer.contact_person;
				}
			},
			{
				className: '',
				"data": 'delivery_date',
				"title": 'Delivery date',
			},
			{
				className: 'text-center',
				"data": 'status',
				"title": 'Status',
				"render":function(data){
					if (data == 1) {
						return '<span class="badge badge-success">Completed</span>';
					}else{
						return '<span class="badge badge-warning">Pending</span>';
					}
				}
			},
			{
				className: 'text-center',
				"data": 'total_amount',
				"title": 'Total Amount',
				"render":function(data){
					return money.format(data);
				}
			},
			{
				className: 'width-option-1 text-center',
				width: '15%',
				"data": 'id',
				"orderable": false,
				"title": 'Options',
				"render": function(data, type, row, meta){
					newdata = '';
					newdata += '<a href="{{ route('orders.edit') }}/'+row.id+'" class="btn btn-success btn-sm font-base mt-1" ><i class="fa fa-edit"></i></a> ';
					newdata += ' <button class="btn btn-danger btn-sm font-base mt-1" onclick="delete_orders('+row.id+');" type="button"><i class="fa fa-trash"></i></button>';
					if (row.status == 1) {
						newdata += ' <button class="btn btn-info btn-sm font-base mt-1" type="button" disabled><i class="fa fa-money-bill-alt"></i></button>';

					}else{
						newdata += ' <button class="btn btn-info btn-sm font-base mt-1" title="Mark as paid" onclick="add_payment('+row.id+', \''+row.order_tracking_no+'\', \''+row.total_amount+'\');" type="button"><i class="fa fa-money-bill-alt"></i></button>';						
					}
					return newdata;
				}
			},
		]
	});
}


function delete_orders(id){
	swal({
		title: "Are you sure?",
		text: "Do you want to delete orders?",
		type: "warning",
		showCancelButton: true,
		confirmButtonColor: "#DD6B55",
		confirmButtonText: "Yes",
		closeOnConfirm: false
	},
	function(){
		$.ajax({
			type:"DELETE",
			url:"{{ route('orders.delete') }}/"+id,
			data:{},
			dataType:'json',
			beforeSend:function(){
		},
		success:function(response){
			// console.log(response);
			if (response.status == true) {
				show_orders();
				swal("Success", response.message, "success");
			}else{
				console.log(response);
			}
		},
		error: function(error){
			console.log(error);
		}
		});
	});
}

</script>
@endsection